const carBrands = [
  {
    company: "Audi",
    logo: "./image/Audi/audi.png",
    variants: [
      {
        modelName: "A3",
        year: 2023,
        image: "./image/Audi/A3/Audi.A3.jpg",
        engine: { min: 1197, max: 1984, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 6800000, max: 7680000, currency: "PKR" },
      },
      {
        modelName: "A4",
        year: 2023,
        image: "./image/Audi/A4/Audi.A4.jpg",
        engine: { min: 1395, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 5850000, max: 11030000, currency: "PKR" },
      },
      {
        modelName: "A5",
        year: 2023,
        image: "./image/Audi/A5/Audi.A5.jpg",
        engine: { min: 1395, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 15000000, max: 22800000, currency: "PKR" },
      },
      {
        modelName: "A6",
        year: 2023,
        image: "./image/Audi/A6/Audi.A6.jpg",
        engine: { min: 1987, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 36050000, max: 50030000, currency: "PKR" },
      },
      {
        modelName: "A7",
        year: 2023,
        image: "./image/Audi/A7/Audi.A7.jpg",
        engine: { min: 1990, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Silver", "Navy"],
        price: { min: 16000000, max: 17500000, currency: "PKR" },
      },
      {
        modelName: "A8",
        year: 2023,
        image: "./image/Audi/A8/Audi.A8.jpg",
        engine: { min: 1984, max: 4163, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol & Diesel & Hybrid",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 33000000, max: 500000000, currency: "PKR" },
      },
      {
        modelName: "Q2",
        year: 2023,
        image: "./image/Audi/Q2/Audi.Q2.jpg",
        engine: { min: 999, max: 2100, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Navy", "Gold"],
        price: { min: 33500000, max: 40000000, currency: "PKR" },
      },

      {
        modelName: "Q3",
        year: 2023,
        image: "./image/Audi/Q3/Audi.Q3.jpg",
        engine: { min: 2000, max: 2200, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Blue", "Grey", "Red", "White"],
        price: { min: 19500000, max: 20000000, currency: "PKR" },
      },
      {
        modelName: "Q5",
        year: 2023,
        image: "./image/Audi/Q5/Audi.Q5.jpg",
        engine: { min: 1984, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 27000000, max: 29500000, currency: "PKR" },
      },
      {
        modelName: "Q7",
        year: 2023,
        image: "./image/Audi/Q7/Audi.Q7.jpg",
        engine: { min: 2995, max: 3000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 47000000, max: 49500000, currency: "PKR" },
      },
      {
        modelName: "Q8",
        year: 2023,
        image: "./image/Audi/Q8/Audi.Q8.jpg",
        engine: { min: 2995, max: 3000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Hybrid",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 85000000, max: 87500000, currency: "PKR" },
      },
    ],
  },
  {
    company: "BMW",
    logo: "./image/BMW/bmw.png",
    variants: [
      {
        modelName: "2 Series",
        year: 2023,
        image: "./image/BMW/2 Series/bmw.2Series.jpg",
        engine: { min: 1495, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Green", "Blue", "Brown"],
        price: { min: 34000000, max: 34500000, currency: "PKR" },
      },
      {
        modelName: "5 Series",
        year: 2023,
        image: "./image/BMW/5 Series/bmw.5Series.jpg",
        engine: { min: 1998, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Silver", "Black", "Blue", "Purple"],
        price: { min: 53000000, max: 55500000, currency: "PKR" },
      },
      {
        modelName: "7 Series",
        year: 2023,
        image: "./image/BMW/7 Series/bmw.7Series.jpg",
        engine: { min: 2993, max: 6592, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Hybrid & Electric",
        colors: ["White", "Red", "Blue", "Black", "Grey", "Maroon"],
        price: { min: 177000000, max: 235000000, currency: "PKR" },
      },
      {
        modelName: "X1 Series",
        year: 2023,
        image: "./image/BMW/X1/bmw.X1.jpg",
        engine: { min: 1499, max: 2000, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["White", "Blue", "Black", "Gray"],
        price: { min: 52000000, max: 55000000, currency: "PKR" },
      },
      {
        modelName: "X2 Series",
        year: 2023,
        image: "./image/BMW/X2/bmw.X2.jpg",
        engine: { min: 1499, max: 1998, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Blue", "Yellow", "White", "Black"],
        price: { min: 47000000, max: 49500000, currency: "PKR" },
      },
      {
        modelName: "X3 Series",
        year: 2023,
        image: "./image/BMW/X3 Series/bmw.X3Series.jpg",
        engine: { min: 1998, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Hybrid",
        colors: ["White"],
        price: { min: 45000000, max: 47500000, currency: "PKR" },
      },
      {
        modelName: "X5 Series",
        year: 2023,
        image: "./image/BMW/X5 Series/bmw.X5Series.jpg",
        engine: { min: 2998, max: 3000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Hybrid",
        colors: ["White"],
        price: { min: 59000000, max: 62500000, currency: "PKR" },
      },
      {
        modelName: "X7 Series",
        year: 2023,
        image: "./image/BMW/X7/bmw.X7Series.jpg",
        engine: { min: 2995, max: 3000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["White", "Grey", "Black", "Maroon", "Green", "Brown"],
        price: { min: 71000000, max: 73500000, currency: "PKR" },
      },

      {
        modelName: "i4",
        year: 2022,
        image: "./image/BMW/i4/bmw.i4.jpg",
        engine: { min: 340, max: 400, unit: "hp" },
        transmission: "Automatic",
        fuelType: "Electric",
        colors: ["White", "Red", "Blue", "Black", "Grey", "Maroon"],
        price: { min: 51000000, max: 60000000, currency: "PKR" },
      },
      {
        modelName: "iX",
        year: 2022,
        image: "./image/BMW/iX/bmw.iX.jpg",
        engine: { min: 326, max: 523, unit: "hp" },
        transmission: "Automatic",
        fuelType: "Electric",
        colors: ["White", "Red", "Blue", "Black", "Grey", "Maroon"],
        price: { min: 73000000, max: 76000000, currency: "PKR" },
      },
      {
        modelName: "iX3",
        year: 2021,
        image: "./image/BMW/iX3/bmw.iX3.jpg",
        engine: { min: 281, max: 286, unit: "hp" },
        transmission: "Automatic",
        fuelType: "Electric",
        colors: ["Red", "Black", "White", "Blue", "Grey"],
        price: { min: 99000000, max: 100000000, currency: "PKR" },
      },
    ],
  },
  {
    company: "Changan",
    logo: "./image/Changan/changanLogo.webp",
    variants: [
      {
        modelName: "Alsvin",
        year: 2023,
        image: "./image/Changan/Alsvin/alsvin.jpg",
        engine: { min: 1370, max: 1480, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "White", "Gray"],
        price: { min: 4149000, max: 4999000, currency: "PKR" },
      },
      {
        modelName: "Micro Van",
        year: 2023,
        image: "./image/Changan/Micro Van/microVan.jpg",
        engine: { min: 995, max: 1000, unit: "cc" },
        transmission: "Manual",
        fuelType: "Petrol",
        colors: ["Silver", "Black", "White", "Grey"],
        price: { min: 2799000, max: 2999000, currency: "PKR" },
      },
      {
        modelName: "OshanX7",
        year: 2023,
        image: "./image/Changan/OshanX7/oshanX7.jpg",
        engine: { min: 1495, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gray"],
        price: { min: 8549000, max: 9199000, currency: "PKR" },
      },
      {
        modelName: "Star Truck",
        year: 2023,
        image: "./image/Changan/Star Truck/truck.jpg",
        engine: { min: 995, max: 1000, unit: "cc" },
        transmission: "Manual",
        fuelType: "Petrol",
        colors: ["Silver"],
        price: { min: 2500000, max: 2529000, currency: "PKR" },
      },
    ],
  },
  {
    company: "FAW",
    logo: "./image/FAW/faw.png",
    variants: [
      {
        modelName: "V2",
        year: 2023,
        image: "./image/FAW/V2/v2.jpg",
        engine: { min: 1298, max: 1300, unit: "cc" },
        transmission: "Manual",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 1574000, max: 1600000, currency: "PKR" },
      },
      {
        modelName: "XPVDualAC",
        year: 2023,
        image: "./image/FAW/XPV Dual AC/xpv.jpg",
        engine: { min: 970, max: 1000, unit: "cc" },
        transmission: "Manual",
        fuelType: "Petrol",
        colors: ["Silver"],
        price: { min: 1304000, max: 1344000, currency: "PKR" },
      },
      {
        modelName: "CarrierStandard",
        year: 2023,
        image: "./image/FAW/CarrierStandard/carrierStandard.jpg",
        engine: { min: 970, max: 1000, unit: "cc" },
        transmission: "Manual",
        fuelType: "Petrol",
        colors: ["White"],
        price: { min: 1074000, max: 1100000, currency: "PKR" },
      },
    ],
  },
  {
    company: "Honda",
    logo: "./image/Honda/honda.png",
    variants: [
      {
        modelName: "City",
        year: 2023,
        image: "./image/Honda/City/cityCar.jpg",
        engine: { min: 1199, max: 1497, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Silver", "White"],
        price: { min: 4799000, max: 5979000, currency: "PKR" },
      },
      {
        modelName: "Civic",
        year: 2023,
        image: "./image/Honda/Civic/civic.jpg",
        engine: { min: 1497, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "White"],
        price: { min: 8599000, max: 10199000, currency: "PKR" },
      },
      {
        modelName: "BRV",
        year: 2023,
        image: "./image/Honda/BRV/BRVcar.jpg",
        engine: { min: 1497, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "White"],
        price: { min: 6529000, max: 6575000, currency: "PKR" },
      },
      {
        modelName: "HRV",
        year: 2023,
        image: "./image/Honda/HRV/HRVcar.jpg",
        engine: { min: 1498, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "White"],
        price: { min: 7899000, max: 8199000, currency: "PKR" },
      },
      {
        modelName: "CRV",
        year: 2023,
        image: "./image/Honda/CRV/CRVcar.jpg",
        engine: { min: 1997, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "White"],
        price: { min: 10700000, max: 1100000, currency: "PKR" },
      },
      {
        modelName: "Accord",
        year: 2023,
        image: "./image/Honda/Accord/Accord.jpg",
        engine: { min: 1498, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 15499000, max: 16000000, currency: "PKR" },
      },
    ],
  },
  {
    company: "Hyundai",
    logo: "./image/Hyundai/hyundai.png",
    variants: [
      {
        modelName: "Elantra",
        year: 2023,
        image: "./image/Hyundai/Elantra/Elantra.jpg",
        engine: { min: 1600, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 6599000, max: 7130000, currency: "PKR" },
      },
      {
        modelName: "H100",
        year: 2023,
        image: "./image/Hyundai/HS100/hs100.jpg",
        engine: { min: 2600, max: 2607, unit: "cc" },
        transmission: "Manual",
        fuelType: "Diesel",
        colors: ["White"],
        price: { min: 3789000, max: 3829000, currency: "PKR" },
      },
      {
        modelName: "LoniqHybird",
        year: 2023,
        image: "./image/Hyundai/LoniqHybird/loniq.jpg",
        engine: { min: 1560, max: 1580, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Hybrid",
        colors: ["Black", "Gray", "Green", "Gold", "Navy"],
        price: { min: 7000000, max: 7500000, currency: "PKR" },
      },
      {
        modelName: "Sonata",
        year: 2023,
        image: "./image/Hyundai/Sonata/sonata.jpg",
        engine: { min: 2000, max: 2500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Navy", "Green", "Brown"],
        price: { min: 10329000, max: 11280000, currency: "PKR" },
      },
      {
        modelName: "Santafe",
        year: 2023,
        image: "./image/Hyundai/SantaFe/santaFe.jpg",
        engine: { min: 2397, max: 2400, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Gray", "Green", "Gold", "Navy"],
        price: { min: 18500000, max: 19000000, currency: "PKR" },
      },

      {
        modelName: "Staria",
        year: 2023,
        image: "./image/Hyundai/Staria/staria.jpg",
        engine: { min: 2200, max: 3500, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol & Diesel",
        colors: ["Black", "Gray", "Green", "Gold", "Navy"],
        price: { min: 8364000, max: 11009000, currency: "PKR" },
      },
      {
        modelName: "Tucson",
        year: 2023,
        image: "./image/Hyundai/Tucson/tucson.jpg",
        engine: { min: 1997, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 8230000, max: 8859000, currency: "PKR" },
      },
    ],
  },
  {
    company: "KIA Motor",
    logo: "./image/KIA/kiamotors.png",
    variants: [
      {
        modelName: "GrandCarnival",
        year: 2023,
        image: "./image/KIA/GrandCarnival/carnival.jpg",
        engine: { min: 3497, max: 3500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Black", "Red", "Brown", "Silver", "Yellow"],
        price: { min: 16750000, max: 17500000, currency: "PKR" },
      },
      {
        modelName: "Stonic",
        year: 2023,
        image: "./image/KIA/Stonic/stonic.jpg",
        engine: { min: 1397, max: 1400, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 5350000, max: 5930000, currency: "PKR" },
      },
      {
        modelName: "Picanto",
        year: 2023,
        image: "./image/KIA/Picanto/picanto.jpg",
        engine: { min: 997, max: 1000, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "Black", "Brown", "Gold"],
        price: { min: 3350000, max: 3625000, currency: "PKR" },
      },

      {
        modelName: "Sorento",
        year: 2023,
        image: "./image/KIA/Soranto/soranto.jpg",
        engine: { min: 2400, max: 3500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Grey", "Blue", "Silver", "Red"],
        price: { min: 10400000, max: 11390000, currency: "PKR" },
      },
      {
        modelName: "Sportage",
        year: 2023,
        image: "./image/KIA/Sportage/sportage.jpg",
        engine: { min: 1997, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Blue", "Grey", "Maroon", "White", "Silver", "Red"],
        price: { min: 7050000, max: 9050000, currency: "PKR" },
      },
    ],
  },
  {
    company: "Mercedes-Benz",
    logo: "./image/Mercedes/mercedes.png",
    variants: [
      {
        modelName: "A_Class",
        year: 2023,
        image: "./image/Mercedes/A_Class/Aclass.jpg",
        engine: { min: 1332, max: 1400, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Red", "Silver", "White", "Grey"],
        price: { min: 30000000, max: 32500000, currency: "PKR" },
      },
      {
        modelName: "CLA_Class",
        year: 2023,
        image: "./image/Mercedes/CLA_Class/claClass.jpg",
        engine: { min: 1332, max: 1400, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "White", "Gold", "Gray"],
        price: { min: 52000000, max: 55000000, currency: "PKR" },
      },
      {
        modelName: "G_Class",
        year: 2023,
        image: "./image/Mercedes/G_Class/gClass.jpg",
        engine: { min: 3982, max: 4000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["White", "Black", "Gold"],
        price: { min: 87200000, max: 88000000, currency: "PKR" },
      },
      {
        modelName: "GLB_200",
        year: 2023,
        image: "./image/Mercedes/GLB_200/glb200.jpg",
        engine: { min: 1332, max: 1350, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["White", "Black", "Red", "Navy"],
        price: { min: 35000000, max: 36000000, currency: "PKR" },
      },
      {
        modelName: "Iris_2",
        year: 2023,
        image: "./image/Mercedes/Iris_2/Mercedes-Benz_W206_IMG_6380.jpg",
        engine: { min: 1497, max: 2000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "White", "Gold", "Green"],
        price: { min: 50000000, max: 72000000, currency: "PKR" },
      },
      {
        modelName: "S_Class",
        year: 2023,
        image: "./image/Mercedes/S_Class/sClass.jpg",
        engine: { min: 2997, max: 3000, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "White", "Yellow", "Grey"],
        price: { min: 80000000, max: 82500000, currency: "PKR" },
      },
    ],
  },
  {
    company: "MG",
    logo: "./image/MG/mg.png",
    variants: [
      {
        modelName: "HS",
        year: 2023,
        image: "./image/MG/HS/hs.jpg",
        engine: { min: 1498, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol & Hybrid",
        colors: ["White", "Black"],
        price: { min: 8699000, max: 8725000, currency: "PKR" },
      },
      {
        modelName: "ZS",
        year: 2023,
        image: "./image/MG/ZS/zs.jpg",
        engine: { min: 1497, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Red", "White"],
        price: { min: 5150000, max: 5500000, currency: "PKR" },
      },
      {
        modelName: "ZSEV",
        year: 2023,
        image: "./image/MG/ZSEV/zsev.jpg",
        engine: { min: 141, max: 145, unit: "hp" },
        transmission: "Automatic",
        fuelType: "Electric",
        colors: ["Blue", "Red", "White", "Navy"],
        price: { min: 11600000, max: 12000000, currency: "PKR" },
      },
    ],
  },
  {
    company: "PROTON",
    logo: "./image/Proton/proton.png",
    variants: [
      {
        modelName: "S70",
        year: 2023,
        image: "./image/Proton/S70/s70.jpg",
        engine: { min: 1477, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "White", "Navy"],
        price: { min: 8799000, max: 9299000, currency: "PKR" },
      },
      {
        modelName: "Persona",
        year: 2023,
        image: "./image/Proton/Persona/persona.jpg",
        engine: { min: 1577, max: 1600, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "White", "Navy"],
        price: { min: 8799000, max: 9299000, currency: "PKR" },
      },
      {
        modelName: "SAGA",
        year: 2023,
        image: "./image/Proton/SAGA/saga.jpg",
        engine: { min: 1300, max: 1332, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "White", "Navy"],
        price: { min: 3750000, max: 4100000, currency: "PKR" },
      },
      {
        modelName: "e.MAS 7",
        year: 2025,
        image: "./image/Proton/e.MAS 7/mas7.jpg",
        engine: { min: 1477, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "White", "Navy"],
        price: { min: 8799000, max: 9299000, currency: "PKR" },
      },
      {
        modelName: "X90",
        year: 2023,
        image: "./image/Proton/X90/x90.jpg",
        engine: { min: 1477, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "White", "Navy"],
        price: { min: 8799000, max: 9299000, currency: "PKR" },
      },
      {
        modelName: "X50",
        year: 2023,
        image: "./image/Proton/X50/x50.png",
        engine: { min: 1477, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "White", "Navy"],
        price: { min: 9350000, max: 9500000, currency: "PKR" },
      },
      {
        modelName: "X70",
        year: 2023,
        image: "./image/Proton/X70/x70.png",
        engine: { min: 1500, max: 1800, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "White", "Navy"],
        price: { min: 8800000, max: 9300000, currency: "PKR" },
      },
      {
        modelName: "Iriz",
        year: 2023,
        image: "./image/Proton/Iriz/iriz.jpg",
        engine: { min: 1477, max: 1500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Blue", "Red", "White", "Navy"],
        price: { min: 8799000, max: 9299000, currency: "PKR" },
      },
    ],
  },

  {
    company: "Suzuki",
    logo: "./image/Suzuki/suzuki.png",
    variants: [
      {
        modelName: "APV",
        year: 2023,
        image: "./image/Suzuki/APV/apv.jpg",
        engine: { min: 1493, max: 1590, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["White", "Grey", "Silver", "Blue", "Maroon", "Black"],
        price: { min: 6290000, max: 6325000, currency: "PKR" },
      },
      {
        modelName: "Alto",
        year: 2023,
        image: "./image/Suzuki/Alto/alto.JPG",
        engine: { min: 658, max: 660, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["Maroon", "White", "Blue", "Silver"],
        price: { min: 2251000, max: 2935000, currency: "PKR" },
      },

      {
        modelName: "Bolan",
        year: 2023,
        image: "./image/Suzuki/Bolan/EvereyVan.JPG",
        engine: { min: 796, max: 800, unit: "cc" },
        transmission: "Manual",
        fuelType: "Petrol",
        colors: ["White", "Red", "Silver"],
        price: { min: 1940000, max: 1944000, currency: "PKR" },
      },
      {
        modelName: "Cultus",
        year: 2023,
        image: "./image/Suzuki/Cultus/cultus.png",
        engine: { min: 998, max: 1000, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Silver", "White", "Red", "Blue"],
        price: { min: 3718000, max: 4366000, currency: "PKR" },
      },
      {
        modelName: "CargoVan",
        year: 2023,
        image: "./image/Suzuki/CargoVan/cargoVan.jpg",
        engine: { min: 796, max: 800, unit: "cc" },
        transmission: "Manual",
        fuelType: "Petrol",
        colors: ["White"],
        price: { min: 1940000, max: 2050000, currency: "PKR" },
      },
      {
        modelName: "Jimny",
        year: 2023,
        image: "./image/Suzuki/Jimmy/jimmy.jpg",
        engine: { min: 1462, max: 1500, unit: "cc" },
        transmission: "Manual",
        fuelType: "Petrol",
        colors: ["Silver", "Green", "Black", "White"],
        price: { min: 6049000, max: 6100000, currency: "PKR" },
      },
      {
        modelName: "Ravi",
        year: 2023,
        image: "./image/Suzuki/Ravi/ravi.jpg",
        engine: { min: 796, max: 800, unit: "cc" },
        transmission: "Manual",
        fuelType: "Petrol",
        colors: ["White"],
        price: { min: 1781000, max: 1856000, currency: "PKR" },
      },
      {
        modelName: "Swift",
        year: 2023,
        image: "./image/Suzuki/Swift/swift.jpg",
        engine: { min: 1197, max: 1200, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Blue", "Grey", "Red", "Silver", "White"],
        price: { min: 4256000, max: 4960000, currency: "PKR" },
      },

      {
        modelName: "WagonR",
        year: 2023,
        image: "./image/Suzuki/WagonR/wagonR.png",
        engine: { min: 998, max: 1000, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["White", "Brown", "Silver", "Red"],
        price: { min: 3214000, max: 3741000, currency: "PKR" },
      },
    ],
  },
  {
    company: "Toyota",
    logo: "./image/Toyota/toyota.png",
    variants: [
      {
        modelName: "Corolla",
        year: 2023,
        image: "./image/Toyota/Corolla/corolla.jpg",
        engine: { min: 1298, max: 1800, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Gold", "Grey", "Brown", "Silver", "Blue", "White"],
        price: { min: 6169000, max: 7799000, currency: "PKR" },
      },
      {
        modelName: "CorollaCross",
        year: 2023,
        image: "./image/Toyota/CorollaCross/crossCorolla.jpg",
        engine: { min: 1798, max: 1800, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Hybrid",
        colors: ["Black", "Grey", "Navy", "Blue", "White", "Red"],
        price: { min: 12249000, max: 13419000, currency: "PKR" },
      },
      {
        modelName: "CamryHybrid",
        year: 2023,
        image: "./image/Toyota/CamryHybird/camry.jpg",
        engine: { min: 2487, max: 2500, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol & Hybrid",
        colors: ["Black", "Grey", "Navy", "Blue", "White", "Red"],
        price: { min: 53859000, max: 54100000, currency: "PKR" },
      },
      {
        modelName: "Fortuner",
        year: 2023,
        image: "./image/Toyota/Fortuner/fortuner.png",
        engine: { min: 2694, max: 2755, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol & Diesel",
        colors: ["Black", "Green", "Brown", "Silver", "Blue"],
        price: { min: 15809000, max: 21089000, currency: "PKR" },
      },
      {
        modelName: "HiluxE_Revo",
        year: 2023,
        image: "./image/Toyota/Hilux E_Revo/hilux.jpg",
        engine: { min: 2674, max: 2755, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Diesel",
        colors: ["Black", "Blue", "Grey", "Silver", "White", "Gold"],
        price: { min: 11439000, max: 16149000, currency: "PKR" },
      },
      {
        modelName: "Hiace",
        year: 2023,
        image: "./image/Toyota/Hiace/hiace.jpg",
        engine: { min: 2674, max: 2755, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Diesel",
        colors: ["Gold", "Silver", "White", "Blue"],
        price: { min: 13069000, max: 21029000, currency: "PKR" },
      },
      {
        modelName: "LandCruiserPrado",
        year: 2023,
        image: "./image/Toyota/LandCruiserParado/prado.png",
        engine: { min: 2693, max: 4000, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol & Diesel",
        colors: ["Black", "Green", "Brown", "Silver", "Blue"],
        price: { min: 59109000, max: 95579000, currency: "PKR" },
      },
      {
        modelName: "LandCruiser",
        year: 2023,
        image: "./image/Toyota/LandCruiserGrand/landcruiser.png",
        engine: { min: 3444, max: 3445, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Petrol",
        colors: ["Red", "Black", "Maroon", "Grey", "Silver"],
        price: { min: 156829000, max: 158535000, currency: "PKR" },
      },
      {
        modelName: "PriusNew",
        year: 2023,
        image: "./image/Toyota/PriusNew/prius.jpg",
        engine: { min: 1798, max: 1800, unit: "cc" },
        transmission: "Automatic",
        fuelType: "Hybrid",
        colors: ["Black", "Grey", "Navy", "Blue", "White", "Red"],
        price: { min: 14649000, max: 15055000, currency: "PKR" },
      },
      {
        modelName: "Rush",
        year: 2023,
        image: "./image/Toyota/Rush/rush.jpg",
        engine: { min: 1496, max: 1500, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: ["Black", "Red", "Maroon", "Silver", "White"],
        price: { min: 8009000, max: 8329000, currency: "PKR" },
      },
      {
        modelName: "Yaris",
        year: 2023,
        image: "./image/Toyota/Yaris/yaris.jpg",
        engine: { min: 1329, max: 1496, unit: "cc" },
        transmission: "Manual & Automatic",
        fuelType: "Petrol",
        colors: [
          "Black",
          "Blue",
          "Gold",
          "Grey",
          "Brown",
          "Red",
          "Navy",
          "White",
        ],
        price: { min: 4499000, max: 5969000, currency: "PKR" },
      },
    ],
  },
];

const carColors = {
  Red: "#FF0000",
  Black: "#000000",
  White: "#FFFFFF",
  Blue: "#0000FF",
  Silver: "#C0C0C0",
  Gray: "#808080",
  Green: "#008000",
  Yellow: "#FFFF00",
  Orange: "#FFA500",
  Brown: "#A52A2A",
  Maroon: "#800000",
  Gold: "#FFD700",
  Beige: "#F5F5DC",
  Pink: "#FFC0CB",
  Purple: "#800080",
  Teal: "#008080",
  Navy: "#000080",
  Olive: "#808000",
  Cyan: "#00FFFF",
  Lime: "#00FF00",
};

export { carColors, carBrands };
